### ISSUE TITLE
Not working with 'Tab replace by space' option enabled

### ISSUE THREAD

**Issue by AntonDevil** [dail8859/ElasticTabstops#9]
I tried to open tsv file to check what this plugin is doing.

I opened a file and saw no difference with or without plugin (tried to enable/disable plugin from his menu).
Also, in my Notepad++ I have Settings -> Preferences -> Language -> Tab Settings -> **Replace by space** option enabled, and I thought that this could be the reason and this is!

So, reproducer:
* Open two tsv files (you need two just to be able switching between them, forcing notepad++ to redraw all view)
* Have ElasticTabstops enabled
* Have Replace by space option enabled

When you'll start switching file tabs, you'll see no effect of elastic tabstops.
When you'll disable Replace by space option, and repeat last same actions, you'll see that elastic tabstops took their effect.

**I think ElasticTabstops should be agnostic of Replace by space option =)**

Details:
* **Notepad++ v7.3.3   (32-bit)**
* Build time : Mar  8 2017 - 03:37:37
* Admin mode : OFF
* Local Conf mode : OFF
* **OS : Windows 10 (64-bit)**
* **Elastic Tabstops v1.1**

**Comment by dail8859** [comment]
You are correct that it is automatically disabled for files using the replace by space option. I had originally figured that elastic tabstops wouldn't be needed in that case, but giving it more thought I don't see why it *needs* disabled. It is a simple change and will try to fix it soon.

**Comment by dail8859** [comment]
You can download the new plugin below. Just extract either the 32 or 64 bit zip and copy the DLL file over your existing one and it should work fine. If you run into any problems let me  know.

[ElasticTabstops.zip](https://github.com/dail8859/ElasticTabstops/files/1011338/ElasticTabstops.zip)
[ElasticTabstops_64.zip](https://github.com/dail8859/ElasticTabstops/files/1011339/ElasticTabstops_64.zip)

**Comment by jimbobmcgee** [comment]
Did this ever get pushed into the main N++ plugins list?  I'm running N++ v7.7.1/ETS v1.3 and I still find that, when my *Replace by space* option is set, ETS doesn't appear to work.

I think it must be because ETS never sees the tab press (i.e. it sees the spaces), so doesn't know to do its thing.  I have to go into that N++ preference and disable *Replace by space*, then ETS will recognise tab presses.

Is the *Replace by space* option something that you could override (i.e. on a document-by-document basis) when ETS is enabled?  If so, an additonal plugin menu option to do so would be handy!

**Comment by AntonDevil** [comment]
I have the same config as you do.
N++ v7.7.1/ETS v1.3

ETS still works fine for me regardless of the Replace by space option

**EDIT**
If you'll check the commit that fixed that issue, you'll see that GetUseTabs function is just a dead code. This setting doesn't even considered anywhere. So, I guess, there is something wrong on your side. Maybe some other plugins interfere editor drawing?

**Comment by dail8859** [comment]
> Did this ever get pushed into the main N++ plugins list?

Yes this fix is in v1.3 and later.

> I have the same config as you do.

It could be other plugins or could be a 32 vs 64 bit issue. Could you both post your Notepad++ debug information? (Under the `?` menu)

**Comment by jimbobmcgee** [comment]
Certainly, please find below:

    Notepad++ v7.7.1   (32-bit)
    Build time : Jun 16 2019 - 21:14:50
    Path : C:\Program Files (x86)\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    OS : Windows 10 (64-bit)
    Plugins : BracketsCheck.dll ComparePlugin.dll CsvQuery.dll DSpellCheck.dll ElasticTabstops.dll IndentByFold.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTaskList.dll SQLinFormNpp.dll XMLTools.dll 

For me, ETS only works when my *Settings > Preferences > Language > Tab Settings >Replace by space* option is disabled for the language I am editing.  I have mine enabled at the *[Default]* language level, and only the *normal* language is set to override this.  My tab size is set to 4 chars.  

In any file *other* than a plain text file (i.e. *normal* language), pressing <kbd>Tab</kbd> always inserts four spaces, regardless of whether ETS is enabled or not.  I *have* to uncheck the *Replace by space* option (either at the *[Default]* level or by overriding for the specific language) before ETS behaves as I would expect.

I am wondering if N++'s implementation of *Replace by space* intercepts <kbd>Tab</kbd> and replaces with x spaces *before* your plugin gets a chance to handle the keypress?

**Comment by dail8859** [comment]
Everything seems to be working fine for me. Maybe one of your other plugins is interfering with it.

> I am wondering if N++'s implementation of Replace by space intercepts Tab and replaces with x spaces before your plugin gets a chance to handle the keypress?

No mine catches raw keyboard input before it goes to Notepad++.

See example demo (I used LuaScript to modify the tabs vs spaces):

![et](https://user-images.githubusercontent.com/3694843/63469482-4b2d8d80-c438-11e9-9f4e-30b969d97144.gif)


```
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DoxyIt.dll ElasticTabstops.dll LuaScript.dll mimeTools.dll MyPlugin.dll NppConverter.dll NppExport.dll SurroundSelection.dll 
```

**Comment by jimbobmcgee** [comment]
@dail8859 -- I think we might be talking about two different things -- perhaps I need to explain myself better (and apologies if I am hijacking @AntonDevil's original issue).  

Firstly, I *can* replicate exactly your video, where an existing tab-delimited file is shown to shift the existing column positions in reaction to a new tab that is itself replaced by spaces.

That, however, is not the use-case I was attempting to describe.

My preferred use-case is to use ETS only in certain circumstances.  When editing code, I mostly prefer to work with 4-space indents.  To that end, my *default* language setting is *Replace by space = ticked* and my preferred ETS setting is *Enable = unticked*.

When I decide that I want to use ETS for one particular code file, my natural inclination is to go to *Plugins->ETS->Enable* and tick it, and start my tab-based typing.  However, this does not work, because N++ is still honouring the *Replace by space* option in the main program settings.

For this one-time use, I actually have to go to *Plugins->ETS->Enable* and tick it *and* go to *Settings->Preferences->Language* and untick *Replace by space*; then I have to remember to go back and undo both those settings when I am finished working with aligned text.

What I would *like* to be able to do is just tick *Plugins->ETS->Enable* and have that setting *override* anything that may have been set in the *Settings->Preferences->Language*, and for that override to be reverted automatically when I then untick *Plugins->ETS->Enable*.

Apologies for the crude slideshow GIF below -- hopefully it makes it clearer what I mean...
![ets](https://user-images.githubusercontent.com/12205864/65781631-df7bc600-e143-11e9-80c3-5eb054fc8914.gif)
